#!/usr/bin/env bash
# Bash script that creates a PID file, displays messages, and handles signals

cleanup_and_exit() {
  rm /var/run/myscript.pid
  exit
}

trap 'echo "I hate the kill command" && cleanup_and_exit' SIGTERM
trap 'cleanup_and_exit' SIGQUIT

echo "$$" > /var/run/myscript.pid

while true; do
  echo "To infinity and beyond"
  sleep 2
  trap 'echo "Y U no love me?!"' SIGINT
done
